<?php
/**
 * CreateTaskDTOTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   kiamet MAVOUNGOU
 * @link     https://github.com/paps-app/paps-php-client
 */

/**
 * Paps API
 *
 * The Paps API description
 *
 * OpenAPI spec version: 1.0
 * Contact: mavoungouzenou@gmail.com
 * Generated by: https://github.com/paps-app/paps-php-client.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/paps-app/paps-php-client
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CreateTaskDTOTest Class Doc Comment
 *
 * @category    Class
 * @description CreateTaskDTO
 * @package     Swagger\Client
 * @author      kiamet MAVOUNGOU
 * @link        https://github.com/paps-app/paps-php-client
 */
class CreateTaskDTOTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreateTaskDTO"
     */
    public function testCreateTaskDTO()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "date_pickup"
     */
    public function testPropertyDatePickup()
    {
    }

    /**
     * Test attribute "time_pickup"
     */
    public function testPropertyTimePickup()
    {
    }

    /**
     * Test attribute "vehicle_type"
     */
    public function testPropertyVehicleType()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "receiver"
     */
    public function testPropertyReceiver()
    {
    }

    /**
     * Test attribute "parcels"
     */
    public function testPropertyParcels()
    {
    }
}
