<?php
/**
 * JobDTOTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   kiamet MAVOUNGOU
 * @link     https://github.com/paps-app/paps-php-client
 */

/**
 * Paps API
 *
 * The Paps API description
 *
 * OpenAPI spec version: 1.0
 * Contact: mavoungouzenou@gmail.com
 * Generated by: https://github.com/paps-app/paps-php-client.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/paps-app/paps-php-client
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * JobDTOTest Class Doc Comment
 *
 * @category    Class
 * @description JobDTO
 * @package     Swagger\Client
 * @author      kiamet MAVOUNGOU
 * @link        https://github.com/paps-app/paps-php-client
 */
class JobDTOTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "JobDTO"
     */
    public function testJobDTO()
    {
    }

    /**
     * Test attribute "job_type"
     */
    public function testPropertyJobType()
    {
    }

    /**
     * Test attribute "job_address"
     */
    public function testPropertyJobAddress()
    {
    }

    /**
     * Test attribute "job_date"
     */
    public function testPropertyJobDate()
    {
    }

    /**
     * Test attribute "job_slot_start"
     */
    public function testPropertyJobSlotStart()
    {
    }

    /**
     * Test attribute "job_slot_end"
     */
    public function testPropertyJobSlotEnd()
    {
    }

    /**
     * Test attribute "job_time"
     */
    public function testPropertyJobTime()
    {
    }

    /**
     * Test attribute "job_vehicle_type"
     */
    public function testPropertyJobVehicleType()
    {
    }
}
