<?php
/**
 * ParcelDTOTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   kiamet MAVOUNGOU
 * @link     https://github.com/paps-app/paps-php-client
 */

/**
 * Paps API
 *
 * The Paps API description
 *
 * OpenAPI spec version: 1.0
 * Contact: mavoungouzenou@gmail.com
 * Generated by: https://github.com/paps-app/paps-php-client.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/paps-app/paps-php-client
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ParcelDTOTest Class Doc Comment
 *
 * @category    Class
 * @description ParcelDTO
 * @package     Swagger\Client
 * @author      kiamet MAVOUNGOU
 * @link        https://github.com/paps-app/paps-php-client
 */
class ParcelDTOTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ParcelDTO"
     */
    public function testParcelDTO()
    {
    }

    /**
     * Test attribute "package_size"
     */
    public function testPropertyPackageSize()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "amount_collect"
     */
    public function testPropertyAmountCollect()
    {
    }
}
