<?php
/**
 * ReceiverDTOTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   kiamet MAVOUNGOU
 * @link     https://github.com/paps-app/paps-php-client
 */

/**
 * Paps API
 *
 * The Paps API description
 *
 * OpenAPI spec version: 1.0
 * Contact: mavoungouzenou@gmail.com
 * Generated by: https://github.com/paps-app/paps-php-client.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/paps-app/paps-php-client
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ReceiverDTOTest Class Doc Comment
 *
 * @category    Class
 * @description ReceiverDTO
 * @package     Swagger\Client
 * @author      kiamet MAVOUNGOU
 * @link        https://github.com/paps-app/paps-php-client
 */
class ReceiverDTOTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ReceiverDTO"
     */
    public function testReceiverDTO()
    {
    }

    /**
     * Test attribute "receiver_firstname"
     */
    public function testPropertyReceiverFirstname()
    {
    }

    /**
     * Test attribute "receiver_lastname"
     */
    public function testPropertyReceiverLastname()
    {
    }

    /**
     * Test attribute "receiver_phone_number"
     */
    public function testPropertyReceiverPhoneNumber()
    {
    }

    /**
     * Test attribute "receiver_address"
     */
    public function testPropertyReceiverAddress()
    {
    }

    /**
     * Test attribute "receiver_email"
     */
    public function testPropertyReceiverEmail()
    {
    }

    /**
     * Test attribute "receiver_entreprise"
     */
    public function testPropertyReceiverEntreprise()
    {
    }

    /**
     * Test attribute "receiver_specification_address"
     */
    public function testPropertyReceiverSpecificationAddress()
    {
    }
}
